version: '3.7'

services:
  app-server:
    image: person-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - backend

networks:
  backend: